name: disgem
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - pip
  - python=3.10
  - pytorch=1.12.1
  - pip:
    - black==21.7b0
    - click==8.0.4
    - deepdiff==6.3.0
    - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.3.0/en_core_web_sm-3.3.0-py3-none-any.whl
    - flake8==3.9.2
    - isort==5.9.2
    - notebook
    - transformers==4.19.4
    - spacy==3.3.1
    - tqdm
